### ISSUE TITLE
error when resolution x and y are not equal

### ISSUE THREAD

**Issue by GengPeiLin** [CNES/bulldozer#1]
Hi, 

Thanks for release bulldozer,
I ran it with a 20 cm resolution DSM, it will failed when check if x and y resolution equal to each other.
When I ran a downsampled 30m version, it works but the result was degraded.

Any suggestion to overcome this fine resolution issue?

regards,

GP

**Comment by dimitriLallement** [comment]
Hello,

We're sorry, but Bulldozer isn't designed to take input DSM with unequal x and y resolution. 
In order to modulate the sheet tension, we suggest you modify the `max_object_width` parameter, which should improve your results.

Best regards,

Dimitri
